cloud:
  aws:
    credentials:
      access-key: ASIA2UC3FGMKYS6Z4NYP
      secret-key: KZhlHRUSWguWs89TefAi44M2kWt7hvl+zM0XfAT3
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: assets-dev-glu


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9000